### ISSUE TITLE
A empty query string will create a map with a empty key and value

### ISSUE THREAD

**Issue by adaojunior** [Daegalus/formler#4]
```
print(
 Formler.parseUrlEncoded("")
);
```

will print `{: }`

**Comment by Daegalus** [comment]
Thanks for reporting this. I will take a look tonight when I get home from work. Ill try to fix it asap.

**Comment by adaojunior** [comment]
Thank you

**Comment by Daegalus** [comment]
Fixed in 0.1.1 (which is released to pub), and added tests along with some additional handling of malformed usages.

Hope this helps.
